## Initialization
APT_PACKAGES       = ansible azure-cli
COMMIT_HASH       := $(shell git rev-parse HEAD)
FROM_IMAGE         = ubuntu
FROM_IMAGE_TAG     = 20.04
# This must be treated as a list of 4-tuples and all /s are escaped
FUNCTION_GENERATOR = "terraform" "tfsec" "\/" "recursive scan"
GITHUB             = tfutils/tfenv liamg/tfsec hashicorp/packer
IMAGE_NAME         = easy_infra
UNAME_S           := $(shell uname -s)
VERSION            = 0.4.6
YARN_PACKAGES      = mermaid @mermaid-js/mermaid-cli


## Validation
ifneq ($(UNAME_S),Darwin)
$(error This project currently only supports Darwin)
endif

ifndef COMMIT_HASH
$(error COMMIT_HASH was not properly set)
endif


## Functions
get_github_latest_version = $$(docker run --rm easy_infra:latest "curl -s https://api.github.com/repos/$(1)/releases/latest | jq -r '.tag_name'")
update_dockerfile_package = ./update.sh --package=$(1) --version=$(2)
update_dockerfile_repo    = ./update.sh --repo=$(1) --version=$(2)


## Rules
.PHONY: all
all: update build

.PHONY: update
update: update-functions update-deps

.PHONY: update-deps
update-deps: update-apt update-awscli update-github update-terraform update-yarn


.PHONY: update-functions
update-functions:
	@echo "Updating the functions script..."
	@echo "# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN" > functions
	@cat functions_static >> functions
	@chmod 0755 functions
	@# This method works as long as FUNCTION_GENERATOR is treated like a list of 4-tuples
	@# It was chosen because Make and bash don't natively support multidimensional arrays
	@i=0; for element in $(FUNCTION_GENERATOR); do \
		if (( i % 4 == 0 )) ; then \
		  echo "# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN" >> functions; \
			cat functions_template >> functions; \
			docker run --rm -v $$(pwd):/tmp/ easy_infra:latest "sed -i 's/%FUNCTION_NAME%/$${element}/g' /tmp/functions"; \
		elif (( i % 4 == 1 )) ; then \
			docker run --rm -v $$(pwd):/tmp/ easy_infra:latest "sed -i 's/%SECURITY_TOOL%/$${element}/g' /tmp/functions"; \
		elif (( i % 4 == 2 )) ; then \
			docker run --rm -v $$(pwd):/tmp/ easy_infra:latest "sed -i 's/%SECURITY_TOOL_ARGS%/$${element}/g' /tmp/functions"; \
		elif (( i % 4 == 3 )) ; then \
			docker run --rm -v $$(pwd):/tmp/ easy_infra:latest "sed -i 's/%SECURITY_TOOL_ACTION%/$${element}/g' /tmp/functions"; \
		fi; \
		i=$$((i+1)); \
	done
	@echo "Done!"

.PHONY: build
build:
	@DOCKER_BUILDKIT=1 docker build --rm -t $(IMAGE_NAME):latest -t $(IMAGE_NAME):$(VERSION) -t $(IMAGE_NAME):$(COMMIT_HASH) --build-arg "FROM_IMAGE=$(FROM_IMAGE)" --build-arg "FROM_IMAGE_TAG=$(FROM_IMAGE_TAG)" .

.PHONY: update-apt
update-apt:
	@echo "Updating the apt package versions..."
	@for package in $(APT_PACKAGES); do \
		version=$$(docker run --rm easy_infra:latest "apt-get update &>/dev/null && apt-cache policy $${package} | grep '^  Candidate:' | awk -F' ' '{print \$$NF}'"); \
		$(call update_dockerfile_package,$${package},$${version}); \
	done
	@echo "Done!"

.PHONY: update-awscli
update-awscli: awscli-to-freeze.txt
	@echo "Updating the awscli.txt..."
	@docker run --rm -v $$(pwd):/usr/src/app/ python:3 /bin/bash -c "pip3 install -r /usr/src/app/awscli-to-freeze.txt &>/dev/null && pip3 freeze > /usr/src/app/awscli.txt"
	@echo "Done!"

.PHONY: update-github
update-github:
	@echo "Updating github repo tags..."
	@for repo in $(GITHUB); do \
		version=$(call get_github_latest_version,$${repo}); \
		$(call update_dockerfile_repo,$${repo},$${version}); \
	done
	@echo "Done!"

.PHONY: update-terraform
update-terraform:
	@echo "Updating the terraform version..."
	@version=$$(docker run --rm easy_infra:latest "tfenv list-remote 2>/dev/null | egrep -v '(rc|beta)' | head -1"); \
		$(call update_dockerfile_package,terraform,$${version})
	@echo "Done!"

.PHONY: update-yarn
update-yarn:
	@echo "Updating the yarn package versions..."
	@for package in $(YARN_PACKAGES); do\
		version=$$(docker run --rm easy_infra:latest "yarn info $${package} --json 2>/dev/null | jq -r .data[\\\"dist-tags\\\"].latest"); \
		$(call update_dockerfile_package,$${package},$${version}); \
	done
	@echo "Done!"


.PHONY: push_tag
push_tag:
	@git tag v$(VERSION)
	@git push origin v$(VERSION)

