---
name: "Open a release PR"

on:
  schedule:
    - cron: '42 3 1 * *'

jobs:
  update:
    name: Update
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy --ignore-pipfile --dev
      - name: Create a release
        run: pipenv run invoke release
      - name: Create or update a pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automated release
          commit-message: Automated release
          committer: Seiso Automation <automation@seisollc.com>
          delete-branch: true
          signoff: true
