      - name: Install cosign
        uses: sigstore/cosign-installer@main
      - name: Sign the images
        run:
          for tag in "${TAG#v}-minimal"
                     "${TAG#v}-aws"
                     "${TAG#v}-az"
                     "${TAG#v}"; do
            DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' \
                     "seiso/easy_infra:${tag}" )
            echo -n "${COSIGN_PASSWORD}" |
            cosign sign --key cosign.key
              -a git_sha="${GITHUB_SHA}"
              -a tag="${tag}"
              "seiso/easy_infra@${DIGEST}" ;
          done
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
