---
name: "Release"

on:
  push:
    tags:
      - 'v2[0-1][0-9][0-9].0[0-9].[0-9][0-9]'
      - 'v2[0-1][0-9][0-9].1[0-2].[0-9][0-9]'

jobs:
  release:
    name: Release
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Retrieve the tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> "${GITHUB_ENV}"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy --ignore-pipfile --dev
          mkdir "${RUNNER_TEMP}/bin"
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b "${RUNNER_TEMP}/bin"
          chmod +x "${RUNNER_TEMP}/bin/syft"
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b "${RUNNER_TEMP}/bin"
          chmod +x "${RUNNER_TEMP}/bin/grype"
          echo "${RUNNER_TEMP}/bin" >> "${GITHUB_PATH}"
      - name: Build the images
        run: pipenv run invoke build
      - name: Generate SBOMs
        run: pipenv run invoke sbom
      - name: Upload SBOMs
        uses: actions/upload-artifact@v2
        with:
          name: SBOMs
          path: sbom.*.v*.json
          if-no-files-found: error
      - name: Generate Vuln scan results
        run: pipenv run invoke vulnscan
      - name: Upload Vuln scan results
        uses: actions/upload-artifact@v2
        with:
          name: Vulns
          path: vulns.*.v*.json
          if-no-files-found: error
      - name: Publish the release to GitHub
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.TAG }}
          draft: false
          prerelease: false
          files: |
            sbom.*.v*.json
            vulns.*.v*.json
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish the release README to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: seiso/easy_infra
          short-description: |
            A docker container to secure the use of Infrastructure as Code (IaC) tools
      - name: Publish the release images to Docker Hub
        run: pipenv run invoke publish release
      - name: Install cosign
        uses: sigstore/cosign-installer@main
      - name: Sign the images
        run:
          for tag in "${TAG#v}-minimal"
                     "${TAG#v}-aws"
                     "${TAG#v}-az"
                     "${TAG#v}"; do
            DIGEST=$(docker manifest inspect --verbose "seiso/easy_infra:$tag" |
                     jq -r '.Descriptor.digest') ;
            echo -n "${COSIGN_PASSWORD}" |
            cosign sign --key cosign.key
              -a git_sha="${GITHUB_SHA}"
              -a tag="${tag}"
              "seiso/easy_infra@${DIGEST}" ;
          done
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
