---
name: "Release"

on:
  push:
    tags:
      - 'v2[0-1][0-9][0-9].0[0-9].[0-9][0-9]'
      - 'v2[0-1][0-9][0-9].1[0-2].[0-9][0-9]'

jobs:
  release:
    name: Release
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Create the release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
